on:
  push:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  backfill-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: bcanseco/github-contribution-graph-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_EMAIL: support@rerechanstore.eu.org
          MAX_DAYS: 365
          MIN_COMMITS_PER_DAY: 2
          MAX_COMMITS_PER_DAY: 6
